"""DoiPmidPmcid all fields are not unique

Revision ID: bc753c80081a
Revises: 8bc4fddd9f95
Create Date: 2021-09-27 16:09:20.747731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc753c80081a'
down_revision = '8bc4fddd9f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doi_pmcid_pmid_doi', table_name='doi_pmcid_pmid')
    op.create_index(op.f('ix_doi_pmcid_pmid_doi'), 'doi_pmcid_pmid', ['doi'], unique=False)
    op.drop_index('ix_doi_pmcid_pmid_pmcid', table_name='doi_pmcid_pmid')
    op.create_index(op.f('ix_doi_pmcid_pmid_pmcid'), 'doi_pmcid_pmid', ['pmcid'], unique=False)
    op.drop_index('ix_doi_pmcid_pmid_pmid', table_name='doi_pmcid_pmid')
    op.create_index(op.f('ix_doi_pmcid_pmid_pmid'), 'doi_pmcid_pmid', ['pmid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doi_pmcid_pmid_pmid'), table_name='doi_pmcid_pmid')
    op.create_index('ix_doi_pmcid_pmid_pmid', 'doi_pmcid_pmid', ['pmid'], unique=False)
    op.drop_index(op.f('ix_doi_pmcid_pmid_pmcid'), table_name='doi_pmcid_pmid')
    op.create_index('ix_doi_pmcid_pmid_pmcid', 'doi_pmcid_pmid', ['pmcid'], unique=False)
    op.drop_index(op.f('ix_doi_pmcid_pmid_doi'), table_name='doi_pmcid_pmid')
    op.create_index('ix_doi_pmcid_pmid_doi', 'doi_pmcid_pmid', ['doi'], unique=False)
    # ### end Alembic commands ###
